FORMAT: 1A
HOST: http://www.google.com

# Flappy World
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Languages
Examples related to the languages of the **Flappy World API**

## Notes Collection [/api/languages]
### List all Languages[GET]
+ Response 200 (application/json)

        [{
          "id": 1, "name": "Chinese"
        }, {
          "id": 2, "name": "Spanish"
        }]

## Language [/api/languages/id/{id}]
A single Language object with all its details

### Retrieve a Language by id[GET]
+ Parameters
    + id (required, number, `2`) ... Numeric `id` of the Language perform action with. Has example value.

+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "name": "Spanish", "script": "Latin Alphabet", "description": "Something about Spanish xD", "area": [1, 3, 4], "picture": "http://picture.link.here.jpg" }

### Retrieve a Language by name [GET]
+ Parameters
    + name (required, string, `Spanish`) ... String `name` of the Language perform action with. Has example value.
    
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "name": "Spanish", "script": "Latin Alphabet", "description": "Something about Spanish xD", "area": [1, 3, 4], "picture": "http://picture.link.here.jpg" }
